stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  image: 6d3ea156
  tags:
    - Shell
  script:
    - echo "static analysis"
    - exit 1
  allow_failure: true

unittest:
  stage: Test
  image: 6d3ea156
  tags:
    - Shell
  script:
    - echo "test"
    - exit 1
  allow_failure: true

deploy:
  stage: Deploy
  image: 6d3ea156
  tags:
    - Shell
  script:
    - echo "deploy"
    - exit 1
  allow_failure: true
