stages:
  - Lint
  - Platformio
  - Build
  - Test
  - Deploy

# https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md
# https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
markdownlint:
  stage: Lint
  tags:
    - docker
  image: pipelinecomponents/markdownlint:latest
  script:
    - mdl --style all --warnings --rules ~MD001,~MD004,~MD005,~MD006,~MD007,~MD009,~MD012,~MD013,~MD022,~MD024,~MD025,~MD029,~MD032,~MD033,~MD034,~MD036 .
  allow_failure: true

cpplint:
  image: python:latest
  stage: Lint
  script:
    - pip install cpplint
    - cpplint --filter=-legal --recursive */*
  tags:
    - docker
  allow_failure: true

build:
  stage: Build
  tags:
    - shell
  script:
    - echo "static analysis"
    - exit 0
  allow_failure: true

test-drc:
  stage: Test
  tags:
    - drc
  image: productize/kicad-automation-scripts:latest
  script:
    - export DISPLAY=:0
    - python -m kicad-automation.pcbnew_automation.run_drc ./hardware_package/avionics_pcb/testing/KiCad.kicad_pcb .output
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - exit 0
  allow_failure: true

code-coverage:
  stage: test
  tags:
    - docker
  image: gcc
  script:
    - apt-get update
    - apt-get install -y gcovr
    - cd software_package/code_coverage
    - chmod u+x execute_tests_coverage.sh
    - ./execute_tests_coverage.sh lib/ test/
  artifacts:
    paths:
      - software_package/code_coverage/*.html
    untracked: false
    expire_in: 10 days
  allow_failure: true

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 0
  allow_failure: true

image: python:2.7

before_script:
  - "pip install -U platformio"

# job:
#   stage: Platformio
#   script: "platformio ci --board=adafruit_feather_f405"
#   variables: {PLATFORMIO_CI_SRC: "software_package/src/main.cpp"}
